# Upload sources to Crowdin for translation

name: Crowdin Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'intl/*_us.h'
      - 'intl/*_us.json'

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Checkout
        uses: actions/checkout@v2
      - name: Crowdin Sync
        shell: bash
        env:
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
        run: |
          cd intl
          python3 crowdin_sync.py "$CROWDIN_API_KEY"
