name: CI PSVita

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: git.libretro.com:5050/libretro-infrastructure/libretro-build-vita:latest
      options: --user root

    steps:
    - uses: actions/checkout@v3

    - name: Compile Salamander
      run: |
        make -f Makefile.vita.salamander -j$(getconf _NPROCESSORS_ONLN) clean
        make -f Makefile.vita.salamander -j$(getconf _NPROCESSORS_ONLN)

    - name: Compile RA
      run: |
        make -f Makefile.vita -j$(getconf _NPROCESSORS_ONLN) clean
        make -f Makefile.vita -j$(getconf _NPROCESSORS_ONLN) HAVE_STATIC_DUMMY=1 HAVE_VITAGLES=1
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - uses: actions/upload-artifact@v4
      with:
        name: RA-PSVita-dummy-${{ steps.slug.outputs.sha8 }}
        path: |
          eboot.bin
