# Validates compilation of RetroArch binary

name: RetroArch CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  linux-c89: # Smoketest build using most restrictive compiler and default options
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install build-essential libxkbcommon-dev libx11-xcb-dev zlib1g-dev libfreetype6-dev libegl1-mesa-dev libgles2-mesa-dev libgbm-dev nvidia-cg-toolkit nvidia-cg-dev libavcodec-dev libsdl2-dev libsdl-image1.2-dev libxml2-dev yasm
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: ./configure
      - name: Build
        run: make C89_BUILD=1
      - name: Build Debug
        run: |
          make clean # making sure we don't have leftovers from previous build
          make DEBUG=1 GL_DEBUG=1 C89_BUILD=1
