name: CI webOS

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ run_build ]

env:
  PACKAGE_NAME: com.retroarch.webos
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Download ares-cli-rs
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "webosbrew/ares-cli-rs"
          latest: true
          fileName: "ares-package_*.deb"
          out-file-path: "temp"

      - name: Download Manifest Generator
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "webosbrew/dev-toolbox-cli"
          latest: true
          fileName: "webosbrew-toolbox-gen-manifest_*.deb"
          out-file-path: "temp"

      - name: Update packages
        run: sudo apt-get -yq update

      - name: Install webOS CLI
        run: sudo apt-get -yq install ./temp/*.deb

      - name: Download webOS NDK
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "openlgtv/buildroot-nc4"
          latest: true
          fileName: "arm-webos-linux-gnueabi_sdk-buildroot-x86_64.tar.gz"
          out-file-path: "/tmp"

      - name: Extract webOS NDK
        shell: bash
        working-directory: /tmp
        run: |
          tar xzf arm-webos-linux-gnueabi_sdk-buildroot-x86_64.tar.gz
          ./arm-webos-linux-gnueabi_sdk-buildroot/relocate-sdk.sh

      - name: Load RARCH_VERSION from version.all
        id: version
        shell: bash
        run: |
          RARCH_VERSION=$(grep -Po '(?<=#define PACKAGE_VERSION ")[^"]+' version.all)
          echo "RARCH_VERSION=$RARCH_VERSION" >> "$GITHUB_ENV"

      - name: Compile RA (GLES3 variant)
        shell: bash
        run: |
          . /tmp/arm-webos-linux-gnueabi_sdk-buildroot/environment-setup
          make -f Makefile.webos clean
          make -f Makefile.webos ipk PACKAGE_NAME=${PACKAGE_NAME} ADD_SDL2_LIB=1 \
            HAVE_OPENGLES3=1 HAVE_OPENGLES3_1=1 HAVE_OPENGLES3_2=1 -j"$(getconf _NPROCESSORS_ONLN)"
          mv webos/com.retroarch.webos_${RARCH_VERSION}_arm.ipk \
             webos/com.retroarch.webos.gles3_${RARCH_VERSION}_arm.ipk
        env:
          DEBUG: ${{ github.event_name == 'release' && '0' || '1' }}

      - name: Upload GLES3 artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.retroarch.webos.gles3_${{ env.RARCH_VERSION }}_${{ github.sha }}_arm.ipk
          path: webos/com.retroarch.webos.gles3_${{ env.RARCH_VERSION }}_arm.ipk

      - name: Compile RA (default)
        shell: bash
        run: |
          . /tmp/arm-webos-linux-gnueabi_sdk-buildroot/environment-setup
          make -f Makefile.webos ipk PACKAGE_NAME=${PACKAGE_NAME} ADD_SDL2_LIB=1 -j"$(getconf _NPROCESSORS_ONLN)"
        env:
          DEBUG: ${{ github.event_name == 'release' && '0' || '1' }}

      - name: Upload default artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.retroarch.webos_${{ env.RARCH_VERSION }}_${{ github.sha }}_arm.ipk
          path: webos/com.retroarch.webos_${{ env.RARCH_VERSION }}_arm.ipk

      - name: Generate Manifest (default only)
        if: github.repository == 'webosbrew/Retroarch'
        shell: bash
        run: |
          webosbrew-gen-manifest -o webos/${PACKAGE_NAME}.manifest.json \
              -p webos/${PACKAGE_NAME}_${RARCH_VERSION}_arm.ipk \
              -i https://github.com/webosbrew/RetroArch/raw/webos/webos/icon160.png \
              -l https://github.com/webosbrew/RetroArch

      - name: Release
        if: github.event_name == 'release' && github.repository == 'webosbrew/Retroarch'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          artifacts: |
            webos/com.retroarch.webos_${{ env.RARCH_VERSION }}_arm.ipk
            webos/com.retroarch.webos.gles3_${{ env.RARCH_VERSION }}_arm.ipk
            webos/${{ env.PACKAGE_NAME }}.manifest.json
